-- Add Germany hospitality, Netherlands hospitality, and Belgium companies
-- Appends to existing data — does NOT delete anything.

/*M!999999\- enable the sandbox mode */ 
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (34,'nila-restaurants-berlin','NILA Restaurants Berlin','https://nilakitchen.de/','Restaurant / South Indian / Kerala Food',NULL,2023,'Germany','Berlin','Berlin, Germany','Restaurant / South Indian / Kerala Food company founded by Joby Jose, Melvin Babu in Berlin, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (35,'malabar-restaurant-burgdorf','Malabar Kerala Restaurant','https://malabaronline.eu/','Restaurant / South Indian / Kerala Food',NULL,NULL,'Germany','Burgdorf','Burgdorf, Germany','Restaurant / South Indian / Kerala Food company founded by Shaji Kurian in Burgdorf, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (36,'thanima-kerala-restaurant-hamburg','Thanima Kerala Restaurant','https://www.thanimakeralarestaurant-hamburg.de/','Restaurant / Kerala Food',NULL,NULL,'Germany','Hamburg','Hamburg, Germany','Restaurant / Kerala Food company in Hamburg, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (37,'kerala-kueche-ug-hamburg','Kerala Küche UG (haftungsbeschränkt)',NULL,'Restaurant / Kerala Food / Catering / Food Retail',NULL,2026,'Germany','Hamburg','Hamburg, Germany','Restaurant / Kerala Food / Catering / Food Retail company founded by Soumya Sankaran Padmakshan in Hamburg, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (38,'foodeza','FOODEZA','https://foodeza.de/','Food Truck / Kerala Catering',NULL,NULL,'Germany','Mühlacker','Mühlacker, Germany','Food Truck / Kerala Catering company founded by Jobins, Christeena in Mühlacker, Germany.','approved',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (39,'kerala-kitchen-sankt-augustin','Kerala Kitchen','https://keralakitchen.de/','Catering / Kerala Food',NULL,NULL,'Germany','Sankt Augustin','Sankt Augustin, Germany','Catering / Kerala Food company in Sankt Augustin, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (40,'dixons-kitchen-dortmund','Dixon\'s Kitchen','https://www.dixons-kitchen.de/','Restaurant / South Indian / Kerala Food',NULL,NULL,'Germany','Dortmund','Dortmund, Germany','Restaurant / South Indian / Kerala Food company founded by Dixon Pathrose in Dortmund, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (41,'jhasvik-duesseldorf','Jhasvik','https://jhasvik.de/','Restaurant / South Indian / Kerala Food',NULL,NULL,'Germany','Düsseldorf','Düsseldorf, Germany','Restaurant / South Indian / Kerala Food company founded by Prakash Mohan in Düsseldorf, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (42,'curry-leaves-kerala-restaurant-hannover','Curry Leaves Kerala Restaurant',NULL,'Restaurant / Kerala Food',NULL,NULL,'Germany','Hannover','Hannover, Germany','Restaurant / Kerala Food company in Hannover, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (43,'methi-kerala-restaurant-munich','Methi Kerala Restaurant','https://methi-restaurant.de/','Restaurant / South Indian / Kerala Food',NULL,NULL,'Germany','Höhenkirchen-Siegertsbrunn','Höhenkirchen-Siegertsbrunn, Germany','Restaurant / South Indian / Kerala Food company in Höhenkirchen-Siegertsbrunn, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (44,'kerala-restaurant-munich','Kerala Restaurant','https://www.keralarestaurant.de/','Restaurant / Indian / South Indian',NULL,NULL,'Germany','Munich','Munich, Germany','Restaurant / Indian / South Indian company in Munich, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (45,'kumba-frankfurt','Kumba Indian Restaurant','https://www.kumbafrankfurt.com/','Restaurant / Indian / South Indian / Kerala Food',NULL,NULL,'Germany','Frankfurt','Frankfurt, Germany','Restaurant / Indian / South Indian / Kerala Food company in Frankfurt am Main, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (46,'nilavara-restaurant-frechen','Nilavara Restaurant UG','https://www.instagram.com/nilavararestaurant/','Restaurant / South Indian / Kerala-style Food',NULL,NULL,'Germany','Frechen','Frechen, Germany','Restaurant / South Indian / Kerala-style Food company in Frechen, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (47,'ammas-food-dortmund','Amma\'s Food Dortmund','https://ammasfood.net/','Restaurant / South Indian / Catering',NULL,NULL,'Germany','Dortmund','Dortmund, Germany','Restaurant / South Indian / Catering company in Dortmund, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (48,'southern-spice-aachen','The Southern Spice','https://www.thesouthernspice-aachen.de/','Restaurant / South Indian / Kerala-style Food',NULL,NULL,'Germany','Aachen','Aachen, Germany','Restaurant / South Indian / Kerala-style Food company in Aachen, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (49,'malabar-cafe-brandenburg','Malabar Restaurant & Café','https://www.restaurant-malabar.de/','Restaurant / Café / Indian Food',NULL,NULL,'Germany','Brandenburg an der Havel','Brandenburg an der Havel, Germany','Restaurant / Café / Indian Food company founded by S. Sindhu (listed proprietor) in Brandenburg an der Havel, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (50,'german-malayali-store','German Malayali Store','https://www.germanmalayalistore.de/','Kerala Grocery / Food Retail / Online Retail',NULL,NULL,'Germany','Leverkusen','Leverkusen, Germany','Kerala Grocery / Food Retail / Online Retail company founded by Binish Pappachan Abraham in Leverkusen, Germany.','approved',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (51,'inaivaa-dortmund','Inaivaa','https://www.inaivaa.com/','Kerala Grocery / South Asian Food Retail',NULL,2023,'Germany','Dortmund','Dortmund, Germany','Kerala Grocery / South Asian Food Retail company in Dortmund, Germany.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (52,'wanakam-amsterdam','Wanakam','https://wanakam.club/','Café / Chai Bar / Cultural Space',NULL,NULL,'Netherlands','Amsterdam','Amsterdam, Netherlands','Café / Chai Bar / Cultural Space company founded by Jimmy Varghese, Gaurav Singhal, Shanti Voorn, Manuel Buonamiko in Amsterdam, Netherlands.','approved',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (53,'indian-koffie-house-almere','Indian Koffie House','https://www.indiankoffiehouse.com/','Café / Takeaway / Catering',NULL,NULL,'Netherlands','Almere','Almere, Netherlands','Café / Takeaway / Catering company founded by Naveen Gopi in Almere, Netherlands.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (54,'my-indian-kitchen-eindhoven','My Indian Kitchen',NULL,'Catering / Home Food / Kerala Snacks',NULL,NULL,'Netherlands','Eindhoven','Eindhoven, Netherlands','Catering / Home Food / Kerala Snacks company in Eindhoven, Netherlands.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (55,'indilicious-maastricht','Indilicious','https://www.indilicious.nl/','Catering / Takeaway / Kerala Sadya',NULL,NULL,'Netherlands','Maastricht','Maastricht, Netherlands','Catering / Takeaway / Kerala Sadya company in Maastricht, Netherlands.','pending',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (56,'startupbridge','StartupBridge',NULL,'Startup Advisory / Internationalisation',NULL,NULL,'Belgium','Brussels','Brussels, Belgium','Startup Advisory / Internationalisation company founded by Ebin Ephrem Elavathingal in Brussels, Belgium.','approved',0,'2026-08-25 16:40:38');
INSERT INTO `companies` (`id`, `slug`, `name`, `website`, `industry`, `size`, `founded_year`, `country`, `city`, `location`, `description`, `status`, `verified`, `created_at`) VALUES (57,'ebin-cat-entertainments','CAT Entertainments',NULL,'Digital Media / Production',NULL,NULL,'Belgium','','Belgium connection, Belgium','Digital Media / Production company founded by Ebin Ephrem Elavathingal in Belgium connection, Belgium.','pending',0,'2026-08-25 16:40:38');
/*M!999999\- enable the sandbox mode */ 
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (56,34,'Joby Jose',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (57,34,'Melvin Babu',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (58,35,'Shaji Kurian',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (59,37,'Soumya Sankaran Padmakshan',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (60,38,'Jobins',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (61,38,'Christeena',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (62,40,'Dixon Pathrose',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (63,41,'Prakash Mohan',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (64,49,'S. Sindhu (listed proprietor)',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (65,50,'Binish Pappachan Abraham',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (66,52,'Jimmy Varghese',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (67,52,'Gaurav Singhal',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (68,52,'Shanti Voorn',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (69,52,'Manuel Buonamiko',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (70,53,'Naveen Gopi',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (71,56,'Ebin Ephrem Elavathingal',NULL,NULL,0);
INSERT INTO `founders` (`id`, `company_id`, `name`, `email`, `linkedin`, `show_email`) VALUES (72,57,'Ebin Ephrem Elavathingal',NULL,NULL,0);
/*M!999999\- enable the sandbox mode */ 
INSERT INTO `branches` (`id`, `company_id`, `country`) VALUES (1,19,'Belgium');
