<!doctype html>
<html lang="en"><head><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("consent","default",{ad_storage:"denied",ad_user_data:"denied",ad_personalization:"denied",analytics_storage:"denied"});</script><script src="https://cdn.cookiehub.eu/c2/a2366e42.js"></script><script type="text/javascript">document.addEventListener("DOMContentLoaded",function(event){var cpm={};if(window.cookiehub){window.cookiehub.load(cpm);}});</script><!-- Google tag (gtag.js) --><script async src="https://www.googletagmanager.com/gtag/js?id=G-EJ9D0P01RH"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-EJ9D0P01RH");</script><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Privacy — Kerala Founders</title><meta name="description" content="Kerala Founders' privacy policy — how we collect, use, and protect your information.">
<link rel="canonical" href="https://keralafounders.eu/privacy.php">
<meta property="og:type" content="website"><meta property="og:site_name" content="Kerala Founders"><meta property="og:title" content="Privacy — Kerala Founders"><meta property="og:description" content="Kerala Founders' privacy policy — how we collect, use, and protect your information."><meta property="og:url" content="https://keralafounders.eu/privacy.php">
<meta name="twitter:card" content="summary"><meta name="twitter:title" content="Privacy — Kerala Founders"><meta name="twitter:description" content="Kerala Founders' privacy policy — how we collect, use, and protect your information.">
<link rel="stylesheet" href="assets/style.css"><script src="assets/nav-toggle.js" defer></script><script src="assets/data.php"></script><script src="assets/app.js"></script></head>
<?php include __DIR__ . '/partials/header.php'; ?>
<main id="main">
<section class="section"><div class="wrap" style="max-width:850px"><div class="eyebrow">Privacy</div><h1 style="font-family:Georgia,serif;font-size:55px">Privacy</h1><div class="muted" style="font-size:17px;line-height:1.8"><p>This static demo stores test submissions only in your browser's localStorage. Nothing is sent to Kerala Founders from this version.</p><p>In the production version, submissions will be stored in a database and reviewed before publication. Founders will be able to choose whether their email is displayed publicly.</p><p>This is placeholder website copy and should be replaced with a legally reviewed privacy policy before launch.</p></div></div></section></main><?php include __DIR__ . '/partials/footer-full.php'; ?></body></html>