-- Taxonomy v1.0 migration: add business_type column, remap all existing
-- companies' Industry to the frozen 9-category list, and assign Business Type.
-- Safe to re-run: ADD COLUMN is guarded, UPDATEs are idempotent.

ALTER TABLE companies ADD COLUMN IF NOT EXISTS business_type VARCHAR(60) NOT NULL DEFAULT '' AFTER industry;

UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'veda-naturals';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'spice-route';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'pflege-de-consultancy';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'marble-imaging';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'ready-to-care';
UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'yoga-vihar-berlin';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'markenx';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'acsia-systems-deutschland';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'hire-and-care';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'eternal-ag';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'navirex';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Café' WHERE slug = 'monsoon-beans';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'igcs-consultancy';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'igcs-indo-german-services';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'kolner-visa-zentrum';
UPDATE companies SET industry = 'Professional Services', business_type = 'Professional Practice' WHERE slug = 'kanzlei-saju-jakob';
UPDATE companies SET industry = 'Education', business_type = 'Consultancy' WHERE slug = 'letters-to-abroad';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'goharry-international';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'carve-startup-labs';
UPDATE companies SET industry = 'Education', business_type = 'SME / Local Business' WHERE slug = 'eu-language-institute';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'cied-bv-rightorigins';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'loopit-ai';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'codelattice-netherlands';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'SME / Local Business' WHERE slug = 'charlies-pickles';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'fudd-marketing';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'dot-in';
UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'mindful-yogis';
UPDATE companies SET industry = 'Logistics & Transport', business_type = 'SME / Local Business' WHERE slug = 'beta-group';
UPDATE companies SET industry = 'Healthcare', business_type = 'Medical Practice' WHERE slug = 'sreekrishna-ayurveda';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'adukkala';
UPDATE companies SET industry = 'Construction & Trades', business_type = 'SME / Local Business' WHERE slug = 'solarbase';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala-kitchen-eindhoven';
UPDATE companies SET industry = 'Construction & Trades', business_type = 'Professional Practice' WHERE slug = 'nestabide';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'nila-restaurants-berlin';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'malabar-restaurant-burgdorf';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'thanima-kerala-restaurant-hamburg';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala-kueche-ug-hamburg';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'foodeza';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala-kitchen-sankt-augustin';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'dixons-kitchen-dortmund';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'jhasvik-duesseldorf';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'curry-leaves-kerala-restaurant-hannover';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'methi-kerala-restaurant-munich';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala-restaurant-munich';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kumba-frankfurt';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'nilavara-restaurant-frechen';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'ammas-food-dortmund';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'southern-spice-aachen';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'malabar-cafe-brandenburg';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'german-malayali-store';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'inaivaa-dortmund';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Café' WHERE slug = 'wanakam-amsterdam';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Café' WHERE slug = 'indian-koffie-house-almere';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'my-indian-kitchen-eindhoven';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'indilicious-maastricht';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'startupbridge';
UPDATE companies SET industry = 'Professional Services', business_type = 'SME / Local Business' WHERE slug = 'ebin-cat-entertainments';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kallu-and-co';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'mama-spice';
UPDATE companies SET industry = 'Professional Services', business_type = 'SME / Local Business' WHERE slug = 'girelle-production';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = '3-leaves';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Café' WHERE slug = 'kasi-cafe';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'indian-spice-kitchen';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'olivez';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'pulari-restaurant';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala-royal-caterers';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Startup' WHERE slug = 'smaqo-foods';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'search-indie';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala-kitchen-nykoping';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'atami-sushi-restaurant-denmark';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'little-india-boadilla';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'indian-aderezo';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'prosi-pallikunnel';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'sonnentag-kerala-ayurveda-shop';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'karinkada-ayurveda';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Startup' WHERE slug = 'thinnan';
UPDATE companies SET industry = 'Education', business_type = 'Consultancy' WHERE slug = 'venturevillage';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'gravito';
UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'saraswati';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala-restaurant-lisbon';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'costa-do-malabar';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'swaad';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'curry-clubs';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'hello-coop';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'ayush-consultants';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'jpn-international';
UPDATE companies SET industry = 'Professional Services', business_type = 'Professional Practice' WHERE slug = 'sandeep-soman';
UPDATE companies SET industry = 'Technology', business_type = 'Startup' WHERE slug = 'seal-tech';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'SME / Local Business' WHERE slug = 'yummy-bites-by-jithu';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'best-exotic-kerala-kitchen';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'kalikut-story';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'golden-ratio-limited';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'instamat-cyprus';
UPDATE companies SET industry = 'Professional Services', business_type = 'SME / Local Business' WHERE slug = 'athens-insider';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'd2hire-recruitment';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'naan-bar';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'mez-indo-coastal-cuisine';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'chatterbox-malta';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'michael-paul-zachariah';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'kerala-exotic-supermarket';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'avn-kerala';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'ayaan-sro';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'euro-middle-east';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'euroxis';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'euromaxis-pengattiri';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'SME / Local Business' WHERE slug = 'food-pack';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'bollywood-ljubljana';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'ila-and-co';
UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'maya-ayurveda';
UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'ega-vida-wellness';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'pepper-leaf';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'kerala2krakow';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'SME / Local Business' WHERE slug = 'kalikut-1498';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'kerala-cash-and-carry';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'SME / Local Business' WHERE slug = 'malayali-beer';
UPDATE companies SET industry = 'Retail & E-commerce', business_type = 'SME / Local Business' WHERE slug = 'mercado360-ayurvod';
UPDATE companies SET industry = 'Professional Services', business_type = 'Consultancy' WHERE slug = 'united-kerala-international';
UPDATE companies SET industry = 'Food & Hospitality', business_type = 'Restaurant' WHERE slug = 'madras-bistro';
UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'kera-oriental';
UPDATE companies SET industry = 'Healthcare', business_type = 'SME / Local Business' WHERE slug = 'ayura-ayurveda';
