-- Kerala Founders: import contact-enrichment results (batch 1)
-- Generated from email-enrichment-fixed.csv -- 37 companies with a found contact email.
-- Safe to run regardless of production's current auto-increment state (matches by slug).

UPDATE companies SET contact_email='info@vedanaturals.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://vedanaturals.de/pages/contact-us' WHERE slug='veda-naturals';
UPDATE companies SET contact_email='Contact@thespiceroute.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://thespiceroute.de/contact/' WHERE slug='spice-route';
UPDATE companies SET contact_email='info@pflege-de.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://pflege-de.com/impressum' WHERE slug='pflege-de-consultancy';
UPDATE companies SET contact_email='care@anila-thekkan.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.anila-thekkan.com/' WHERE slug='ready-to-care';
UPDATE companies SET contact_email='info@yogavihar.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://yogavihar.de/' WHERE slug='yoga-vihar-berlin';
UPDATE companies SET contact_email='info@hireandcare.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://hireandcare.de/contact/' WHERE slug='hire-and-care';
UPDATE companies SET contact_email='hello@eternal.ag', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://eternal.ag/en/imprint' WHERE slug='eternal-ag';
UPDATE companies SET contact_email='info@igcsvisa.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://igcsvisa.de/impressum/' WHERE slug='igcs-consultancy';
UPDATE companies SET contact_email='info@igcsvisa.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://igcsvisa.de/impressum/' WHERE slug='igcs-indo-german-services';
UPDATE companies SET contact_email='info@k-v-z.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://k-v-z.de/kontakt/' WHERE slug='kolner-visa-zentrum';
UPDATE companies SET contact_email='info@kanzlei-sajujakob.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://kanzlei-sajujakob.de/kontakt/' WHERE slug='kanzlei-saju-jakob';
UPDATE companies SET contact_email='info@letterstoabroad.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://letterstoabroad.com/' WHERE slug='letters-to-abroad';
UPDATE companies SET contact_email='info@carvestartuplabs.com', email_type='Business/public contact', email_source='Company LinkedIn', email_confidence='Medium', email_source_url='https://de.linkedin.com/company/carvestartuplabs' WHERE slug='carve-startup-labs';
UPDATE companies SET contact_email='nestabide@gmail.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://nestabide.com/' WHERE slug='nestabide';
UPDATE companies SET contact_email='foodezacuisine@gmail.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://foodeza.de/' WHERE slug='foodeza';
UPDATE companies SET contact_email='mail@keralakitchen.de', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://keralakitchen.de/' WHERE slug='kerala-kitchen-sankt-augustin';
UPDATE companies SET contact_email='info@kumbafrankfurt.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.kumbafrankfurt.com/' WHERE slug='kumba-frankfurt';
UPDATE companies SET contact_email='s.asvini@hotmail.de', email_type='Business/public contact', email_source='Official website/imprint', email_confidence='High', email_source_url='https://ammasfood.net/' WHERE slug='ammas-food-dortmund';
UPDATE companies SET contact_email='mail@restaurant-malabar.de', email_type='Business/public contact', email_source='Business directory / tourism listing', email_confidence='Medium', email_source_url='https://www.brandenburg-tourism.com/poi/havelland/gastronomy/restaurant-malabar/' WHERE slug='malabar-cafe-brandenburg';
UPDATE companies SET contact_email='germanmalayalistore@gmail.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.germanmalayalistore.de/contact' WHERE slug='german-malayali-store';
UPDATE companies SET contact_email='info@inaivaa.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.inaivaa.com/visit-store' WHERE slug='inaivaa-dortmund';
UPDATE companies SET contact_email='info@indilicious.nl', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.indilicious.nl/' WHERE slug='indilicious-maastricht';
UPDATE companies SET contact_email='contact@mama-spice.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://mama-spice.com/' WHERE slug='mama-spice';
UPDATE companies SET contact_email='christophe@girelle.com', email_type='Business/public contact', email_source='Industry directory', email_confidence='Medium', email_source_url='https://www.afca.asso.fr/professionnels/structures/1224%2CGirelle-Production' WHERE slug='girelle-production';
UPDATE companies SET contact_email='olivezireland@gmail.com', email_type='Business/public contact', email_source='Official booking site', email_confidence='High', email_source_url='https://booking.olivez.ie/' WHERE slug='olivez';
UPDATE companies SET contact_email='pularidesicafe@gmail.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.pulari.ie/' WHERE slug='pulari-restaurant';
UPDATE companies SET contact_email='keralaroyalcaters@gmail.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.royalcatersdublin.com/contact.html' WHERE slug='kerala-royal-caterers';
UPDATE companies SET contact_email='odense@atami.dk', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://atami.dk/kontakt' WHERE slug='atami-sushi-restaurant-denmark';
UPDATE companies SET contact_email='info@gravito.net', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.gravito.net/contact/' WHERE slug='gravito';
UPDATE companies SET contact_email='info@saraswati.fi', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.saraswati.fi/' WHERE slug='saraswati';
UPDATE companies SET contact_email='contact@costadomalabar.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.costadomalabar.com/contact/' WHERE slug='costa-do-malabar';
UPDATE companies SET contact_email='alex@curryclubs.com', email_type='Business/public contact', email_source='Official site', email_confidence='High', email_source_url='https://curryclubs.com/Home/Restaurants?RestaurantID=UyA2XRRGcGhSeERjCZW9lA%3D%3D' WHERE slug='curry-clubs';
UPDATE companies SET contact_email='info@d2hire.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://d2hire.com/contact/' WHERE slug='d2hire-recruitment';
UPDATE companies SET contact_email='info@naanbar.com', email_type='Business/public contact', email_source='Official event PDF / website', email_confidence='High', email_source_url='https://www.naanbar.com/' WHERE slug='naan-bar';
UPDATE companies SET contact_email='foodpackslovenia@gmail.com', email_type='Business/public contact', email_source='Business registry/directory', email_confidence='Medium', email_source_url='https://www.companywall.si/podjetje/food-pack-doo/MMC1uJXR' WHERE slug='food-pack';
UPDATE companies SET contact_email='info@mayaayurveda.com', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://www.mayaayurveda.com/' WHERE slug='maya-ayurveda';
UPDATE companies SET contact_email='malayali@malayali.rocks', email_type='Business/public contact', email_source='Official website', email_confidence='High', email_source_url='https://malayali.rocks/' WHERE slug='malayali-beer';
