<?php

$KF_COUNTRIES = [
    'Austria' => ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Purkersdorf'],
    'Belgium' => ['Brussels', 'Antwerp', 'Ghent', 'Leuven'],
    'Bulgaria' => ['Sofia', 'Plovdiv', 'Varna'],
    'Croatia' => ['Zagreb', 'Split', 'Rijeka'],
    'Cyprus' => ['Nicosia', 'Limassol', 'Larnaca'],
    'Czechia' => ['Prague', 'Brno', 'Ostrava'],
    'Denmark' => ['Copenhagen', 'Aarhus', 'Odense'],
    'Estonia' => ['Tallinn', 'Tartu'],
    'Finland' => ['Helsinki', 'Espoo', 'Tampere'],
    'France' => ['Paris', 'Lyon', 'Marseille', 'Toulouse'],
    'Germany' => ['Berlin', 'Hamburg', 'Munich', 'Frankfurt', 'Cologne', 'Bad Rappenau', 'Bremen', 'Düsseldorf', 'Koblenz', 'Regensburg', 'Bonn', 'Aachen', 'Brandenburg an der Havel', 'Burgdorf', 'Dortmund', 'Frechen', 'Hannover', 'Höhenkirchen-Siegertsbrunn', 'Leverkusen', 'Mühlacker', 'Sankt Augustin'],
    'Greece' => ['Athens', 'Thessaloniki'],
    'Hungary' => ['Budapest', 'Debrecen'],
    'Ireland' => ['Dublin', 'Cork', 'Galway', 'Ashbourne'],
    'Italy' => ['Rome', 'Milan', 'Turin', 'Bologna'],
    'Latvia' => ['Riga', 'Daugavpils'],
    'Lithuania' => ['Vilnius', 'Kaunas', 'Klaipėda'],
    'Luxembourg' => ['Luxembourg', 'Belvaux'],
    'Malta' => ['Valletta', 'Birkirkara', "St Julian's", "St Paul's Bay", 'Floriana'],
    'Netherlands' => ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Heerlen', 'Best', 'Nieuwegein', 'Egmond aan Zee', 'Eindhoven', 'Delft', 'Almere', 'Maastricht'],
    'Poland' => ['Warsaw', 'Kraków', 'Wrocław', 'Gdańsk'],
    'Portugal' => ['Lisbon', 'Porto', 'Braga', 'Albufeira'],
    'Romania' => ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Ploiești'],
    'Slovakia' => ['Bratislava', 'Košice', 'Gabčíkovo'],
    'Slovenia' => ['Ljubljana', 'Maribor', 'Domanjševci'],
    'Spain' => ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Boadilla del Monte', 'Valladolid'],
    'Sweden' => ['Stockholm', 'Gothenburg', 'Malmö', 'Nyköping'],
];

$KF_INDUSTRIES = [
    'AI / Software',
    'Food / Beverage',
    'Financial Technology',
    'Health / Wellness',
    'Media / Creative',
    'Professional Services',
    'Retail / Consumer',
    'Industrial / Manufacturing',
    'Aerospace / Earth Observation',
    'Agritech / Robotics / AI',
    'AI / AgTech / Supply Chain / Sustainability',
    'AI / Automotive / InsurTech',
    'AI / Software / Digital',
    'Automotive Software / Mobility / AI',
    'Business / Immigration / Legal Services',
    'Business / Immigration Services',
    'Cleantech / Solar / Circular Economy',
    'Coffee / Food & Beverage',
    'Construction / Architecture / Climate Resilience',
    'Digital / Food Marketing',
    'Education / Language',
    'Education / Student Community / Digital',
    'Food / Consumer',
    'Food Manufacturing / Cashew / Distribution / Logistics / Trading',
    'Healthcare / Ayurveda / Wellness',
    'Healthcare Recruitment / HR',
    'Healthcare Recruitment / HR Tech',
    'Healthcare Recruitment / Relocation',
    'Healthcare Recruitment / Training',
    'Legal / Business Consultancy',
    'Marketing / Digital',
    'Restaurant / Catering',
    'Restaurant / Catering / Cloud Kitchen',
    'Restaurant / Food & Beverage',
    'Restaurant / Kerala Food',
    'Solar / Renewable Energy / Engineering',
    'Food Technology',
    'Manufacturing / Ayurveda / Consumer Products',
    'Education / Research Facilitation',
    'Startup Advisory / Innovation',
    'Visa / Immigration Services',
    'Wellness / Ayurveda / Consumer Health',
    'Wellness / Yoga',
    'Wellness / Yoga / Ayurveda',
    'Catering / Home Food / Kerala Snacks',
    'Catering / Kerala Food',
    'Catering / Takeaway / Kerala Sadya',
    'Digital Media / Production',
    'Food Truck / Kerala Catering',
    'Kerala Grocery / Food Retail / Online Retail',
    'Kerala Grocery / South Asian Food Retail',
    'Restaurant / Café / Indian Food',
    'Restaurant / Indian / South Indian',
    'Restaurant / Indian / South Indian / Kerala Food',
    'Restaurant / South Indian / Catering',
    'Restaurant / South Indian / Kerala Food',
    'Restaurant / South Indian / Kerala-style Food',
    'Startup Advisory / Internationalisation',
    'Other',
];

$KF_SIZES = ['1–10', '11–50', '51–200', '201–500', '500+'];
